kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: galasa-ecosystem-operator
  namespace: jdavies47
subjects:
- kind: ServiceAccount
  name: galasa-ecosystem-operator
roleRef:
  kind: Role
  name: galasa-ecosystem-operator
  apiGroup: rbac.authorization.k8s.io
