# /*
#  * Copyright contributors to the Galasa Project
#  */
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: galasaapicomponents.galasa.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: galasa
    version: "v2alpha1"
spec:
  group: galasa.dev
  versions:
  - name: v2alpha1
    served: true
    storage: true
    additionalPrinterColumns:
      - name: Created
        type: string
        jsonPath: ".metadata.creationTimestamp"
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
  names:
    kind: GalasaApiComponent
    plural: galasaapicomponents
    categories:
    - galasa
    - galasa-ecosystems
  scope: Namespaced