apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: galasaenginecontrollercomponents.galasa.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: galasa
    version: "v2alpha1"
spec:
  group: galasa.dev
  versions:
  - name: v2alpha1
    served: true
    storage: true
    additionalPrinterColumns:
      - name: Created
        type: string
        jsonPath: ".metadata.creationTimestamp"
    schema:
      openAPIV3Schema:
        type: object
        # One can use x-kubernetes-preserve-unknown-fields: true
        # at the root of the schema (and inside any properties, additionalProperties)
        # to get the traditional CRD behaviour that nothing is pruned, despite
        # setting spec.preserveUnknownProperties: false.
        #
        # See https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
        # See issue: https://github.com/knative/serving/issues/912
        x-kubernetes-preserve-unknown-fields: true
    # Opt into the status subresource so metadata.generation
    # starts to increment
    subresources:
      status: {}
  names:
    kind: GalasaEngineControllerComponent
    plural: galasaenginecontrollercomponents
    categories:
    - galasa
    - galasa-ecosystems
  scope: Namespaced